### ISSUE TITLE
Snell room reservations

### ISSUE THREAD

**Issue by kylesferrazza** [ninest/huskinfo#10]
https://northeastern.libcal.com/reserve/

**Comment by kylesferrazza** [comment]
I couldn't even find this one in the Student Hub...

**Comment by ninest** [comment]
Thanks! I'm not entirely sure which category it belongs to, so I've put it under services for now.

Also, would you like to be credited? There's a small section at the bottom of the [contribute](https://husker.vercel.app/contribute) page!

**Comment by kylesferrazza** [comment]
> Also, would you like to be credited? There's a small section at the bottom of the [contribute](https://husker.vercel.app/contribute) page!

Sure, thanks! And I'll definitely open more issues / PRs if I think of anything else.
