### ISSUE TITLE
New App to add

### ISSUE THREAD

**Issue by Vocaloiid** [ninest/huskinfo#2]
I'm probably doing this really wrong, but someone made this new course rating system that could go alongside TRACE. Idk if you'd like to add it but here's the link https://ratemycourses.io/NEU

**Comment by ninest** [comment]
Thanks a lot! I added it under Courses: https://docs.google.com/spreadsheets/d/1EpqttYamRgsOIj84_t19SymIuXhD1fgbg6EG1zIoMJM/edit#gid=2024316264
