### ISSUE TITLE
Degree Audit is incorrect for PhD students

### ISSUE THREAD

**Issue by maxvonhippel** [ninest/huskinfo#20]
The correct PhD student degree audit link is [here](https://uagr.northeastern.edu/SelfService) or accessible via:

> Student Hub -> Resources -> Academics, Classes & Registration -> Graduate/Law Interactive Degree Audit

It would be fantastic if Husker could list the undergraduate and graduate degree audit links, under Courses.  Rather than just the undergraduate one.  Thanks!

**Comment by ninest** [comment]
Thanks for the link. Is the same one for Graduate, Law, and PhD?

**Comment by maxvonhippel** [comment]
Yes, that is my understanding.
