### ISSUE TITLE
add onthehub

### ISSUE THREAD

**Issue by kylesferrazza** [ninest/huskinfo#8]
onthehub has free and discounted software.

This link goes to sign-in with SSO, and then redirects to the product list:
https://neu.onthehub.com/WebStore/Security/SignIn.aspx?rurl=%2fWebStore%2fProductsByMajorVersionList.aspx%3f

**Comment by kylesferrazza** [comment]
also thanks for this project! very useful and I never have to look at sharepoint

**Comment by ninest** [comment]
Thanks for the PR!

Glad you're finding it useful! Feel free to suggest any other changes!
